Repository Chirag-Mathur/hello-world, pull requests merged in 2020-10, with the labels that each got.

#8 Count Sort implementation in java
  Q1Count.java
  Q3Bucket.java
  RadixSort.java
  pythongeneratedemail.py
Labels: hacktoberfest-accepted

#9 Simple python program to plot graph
  graphplot.py
Labels: hacktoberfest-accepted

#12 Create binarySearchTree.cpp
  binarySearchTree.cpp
Labels: hacktoberfest-accepted

#11 add Smallest KMP solution in Python
  Smallest_KMP.py
Labels: hacktoberfest-accepted

#10 Binary Search implementation in java
  binary.java
Labels: hacktoberfest-accepted

#14 add CHEFWED solution
  CHEFWED.cpp
Labels: hacktoberfest-accepted

#15 program for overloading '+' operator for complex number
  complesNumber.cpp
Labels: hacktoberfest-accepted

#13 Bubble sort implementation in java.
  bubble.java
Labels: hacktoberfest-accepted

#16 Create CRDGAME3.cpp
  CRDGAME3.cpp
Labels: hacktoberfest-accepted

#18 Create LINCHESS.cpp
  CHEFWARS.cpp
  LINCHESS.cpp
Labels: good first issue, hacktoberfest-accepted

#17 Overload '-' operator to get difference of two dates
  date.cpp
Labels: enhancement, good first issue, hacktoberfest-accepted

#20 Create BHPORSRP.py
  BHPORSRP.py
Labels: hacktoberfest-accepted

#22 Create PTMSSNG.py
  PTMSSNG.py
Labels: hacktoberfest-accepted

#25 Implementation of AVL Trees in CPP
  AvlTrees.cpp
  Screenshot (1602).png
Labels: hacktoberfest-accepted

#24 Create CRDGAME.py
  CRDGAME.py
Labels: hacktoberfest-accepted

#19 Selection sort implementation in java.
  Selection.class
Labels: hacktoberfest-accepted

#27 Create EOEO.py
  EOEO.py
Labels: hacktoberfest-accepted

#26 Create CHEFSTR1.py
  CHEFSTR1.py
Labels: hacktoberfest-accepted

#31 Updated ReadMe with Proper Instructions
  README.md
Labels: hacktoberfest-accepted

#34 Create GrakinForces folder
  GrakinForces/Solution
Labels: hacktoberfest-accepted

#37 added folder and file for CF Round 673-Div2 674-Div3 Grankforces
  CF ROUND 673 DIV_2/A_Copy_paste.cpp
  CF ROUND 673 DIV_2/B_Two_Arrays.cpp
  CF ROUND 673 DIV_2/C_k_Amazing_Numbers.cpp
  CF Round 674 DIV_3/A_Floor_Number.cpp
  CF Round 674 DIV_3/B_Symmetric_Matrix.cpp
  CF Round 674 DIV_3/C_Increase_and_Copy.cpp
  CF Round 674 DIV_3/D_Non_zero_Segments.cpp
  CF Round 674 DIV_3/E_Rock_Paper_Scissors.cpp
  GrakinForces/A_Circle_Coloring.cpp
Labels: enhancement, hacktoberfest-accepted

#41 added cfRound670 folder with description file
  cfRound670d2/description
Labels: hacktoberfest-accepted

#46 Create B_Array_Sum.cpp
  GrakinForces/B_Array_Sum.cpp
Labels: hacktoberfest-accepted

#47 Added Solution to problem C of GrankForces
  GrakinForces/C_Discrete_Accelaration.cpp
Labels: hacktoberfest-accepted

#48 Hello world in C
  hello_world.c
Labels: hacktoberfest-accepted

#50 Added Solution to round 673 div2 problem D
  CF ROUND 673 DIV_2/D_Make_Them_equal.cpp
Labels: hacktoberfest-accepted

#49 fibonacci series in C
  Converting degree Centigrate to Fehrenhite.c
Labels: hacktoberfest-accepted

#29 add hardening rights script
  hardening-folder-rights.sh
Labels: hacktoberfest-accepted

#38 Floyd Warshall Algorithm
  Floyd Warshall Algorithm.cpp
Labels: hacktoberfest-accepted

#42 Heap Sorting of a any given array
  HeapSort.cpp
Labels: hacktoberfest-accepted

#61 Sum of n natural numbers in C
  sum of n natura no..c
Labels: hacktoberfest-accepted

#60 Create hello_world.dart
  README.md
  dart/hello_word.dart
Labels: good first issue, hacktoberfest-accepted

#59 Create hello_world.go
  hello_world.go
Labels: good first issue, hacktoberfest-accepted

#62 Create CHFNSWAP.cpp
  CHFNSWAP.cpp
Labels: hacktoberfest-accepted

#58 added shell_Sort
  shell_sort.py
Labels: hacktoberfest-accepted

#64 Create DFS_BFS_OF_TREE.cpp
  DFS_BFS_OF_TREE.cpp
Labels: hacktoberfest-accepted

#63 Simple calculator functions using switch case(for two numbers)
  swapping_two_numbers.c
  switch case(simple calculator funtions).c
Labels: hacktoberfest-accepted

#65 Create automorphic_neon_magic_number.c
  automorphic_neon_magic_number.c
Labels: hacktoberfest-accepted

#66 Create diwali_lights_hackerrank.c
  diwali_lights_hackerrank.c
Labels: hacktoberfest-accepted

#67 Codeforces Round672 div 2problem C
  cfRound672 problem C
Labels: hacktoberfest-accepted

#51 Update readme
  README.md
Labels: hacktoberfest-accepted

#68 Added Kadanes Algorithm
  kadanes_algorithm/bin/Debug/kadanes_algorithm.exe
  kadanes_algorithm/kadanes_algorithm.cbp
  kadanes_algorithm/kadanes_algorithm.depend
  kadanes_algorithm/main.cpp
  kadanes_algorithm/obj/Debug/main.o
Labels: hacktoberfest-accepted

#28 Create XYSTR.py
  XYSTR.py
Labels: hacktoberfest-accepted

#69 Added Fibbonacci algo using recursion
  BubbleSort_using_recursion/BubbleSort_using_recursion.cbp
  BubbleSort_using_recursion/bin/Debug/BubbleSort_using_recursion.exe
  BubbleSort_using_recursion/main.cpp
  BubbleSort_using_recursion/obj/Debug/main.o
  fibonnacci_using_recursion/bin/Debug/fibonnacci_using_recursion.exe
  fibonnacci_using_recursion/fibonnacci_using_recursion.cbp
  fibonnacci_using_recursion/fibonnacci_using_recursion.depend
  fibonnacci_using_recursion/main.cpp
  fibonnacci_using_recursion/obj/Debug/main.o
Labels: hacktoberfest-accepted
